name: Generate Release Notes
author: Blaise Schaeffer
description: Generate release notes from a GitHub repository.

inputs:
  repository:
    description: Repository name with owner. For example, Microsoft/Typescript.
    type: string
    required: false
    default: ${{ github.repository }}
  tagName:
    description: >
      The tag name for the release.
      This can be an existing tag or a new one.
    type: string
    required: true
  targetCommitish:
    description: >
      Specifies the commitish value that will be
      the target for the release's tag. Required
      if the supplied tag_name does not reference
      an existing tag. Ignored if the tag_name
      already exists.
    type: string
    required: true
  previousTagName:
    description: >
      The name of the previous tag to use as the
      starting point for the release notes. Use
      to manually specify the range for the set
      of changes considered as part this release.
    type: string
    required: false
    default: ''
  configurationFilePath:
    description: >
      Specifies a path to a file in the repository
      containing configuration settings used for
      generating the release notes. If unspecified,
      the configuration file located in the repository
      at '.github/release.yml' or '.github/release.yaml'
      will be used. If that is not present, the default
      configuration will be used.
    type: string
    required: false
    default: ''
  token:
    description: GitHub or personal access token (PAT) used to fetch repository details.
    type: string
    required: false
    default: ${{ github.token }}

outputs:
  name:
    description: Name of the release.
  body:
    description: Generated release notes.

runs:
  using: node20
  main: dist/index.js
